# log_level = "debug"
log_level = "quiet"

[rocklet]
name = "unmake"
identifier = "com.github.mcandre.unmake"
rev = "1"
maintainer = "Andrew Pennebaker <n4jm4@pm.me>"
manufacturer = "YelloSoft"
summary = "a makefile linter"
description = "unmake is a makefile linter emphasizing portability. We target the POSIX make standard."
copyright = "Copyright (C) 2023 Andrew Pennebaker"
license = "0BSD"
url = "https://github.com/mcandre/unmake"

[[pkg]]
image = "n4jm4/rockhopper:0.0.23-macos"
rocklet.oci_arch = "linux/amd64"
rocklet.os_arch = "x86_64"
dest."usr/local/bin" = ".crit/bin/unmake/x86_64-apple-darwin"

[[pkg]]
image = "n4jm4/rockhopper:0.0.23-macos"
rocklet.oci_arch = "linux/arm64"
rocklet.os_arch = "arm64"
dest."usr/local/bin" = ".crit/bin/unmake/aarch64-apple-darwin"

[[pkg]]
image = "n4jm4/rockhopper:0.0.23-ubuntu"
rocklet.oci_arch = "linux/amd64"
dest."usr/bin" = ".crit/bin/unmake/x86_64-unknown-linux-musl"

[[pkg]]
image = "n4jm4/rockhopper:0.0.23-ubuntu"
rocklet.oci_arch = "linux/arm64"
dest."usr/bin" = ".crit/bin/unmake/aarch64-unknown-linux-musl"
