---
name: "Actionlint"
on: # yamllint disable-line rule:truthy
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Actionlint:
    runs-on: "ubuntu-24.04"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "raven-actions/actionlint@v2"
