---
name: "Test-Futureproof-Language"
on: # yamllint disable-line rule:truthy
  push:
  pull_request:
  # POSIX cron format
  # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html
  schedule:
  # Once every 5 minutes
  # - cron: "*/5 * * * *"
  # Once a day
  - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  contents: "read"
  issues: "write"
  pull-requests: "write"
jobs:
  Test-Futureproof-Language:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v7"
    - uses: "actions/setup-go@v7"
      with:
        go-version: "stable"
    - uses: "dtolnay/rust-toolchain@stable"
      with:
        toolchain: "stable"
    - name: "provision dev tools"
      run: "make -f install.mk"
    - run: "make test"
