---
name: "Test-Futureproof-OS"
on: # yamllint disable-line rule:truthy
  push:
  pull_request:
  # POSIX cron format
  # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html
  schedule:
  # Once every 5 minutes
  # - cron: "*/5 * * * *"
  # Once a day
  - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  Test-Futureproof-OS:
    runs-on: "ubuntu-24.04"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "dtolnay/rust-toolchain@stable"
      with:
        toolchain: "1.87.0"
    - name: "provision dev tools"
      run: "make -j 4 crates"
    - run: "tinyrick test"
